### ISSUE TITLE
Problems with Clion EAP

### ISSUE THREAD

**Issue by azat-ismagilov** [AlexeyDmitriev/JHelper#110]
I have problems, after last clion update.

CLion 2019.1 EAP
Build #CL-191.5849.15, built on February 26, 2019
CLion EAP User
Expiration date: March 28, 2019
JRE: 1.8.0_202-release-1483-b31 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.20.7-arch1-1-ARCH

Stacktrace: 
java.lang.AbstractMethodError
	at com.intellij.execution.ExecutionTarget.canRun(ExecutionTarget.java:49)
	at com.intellij.execution.ExecutionTargetManagerImpl.lambda$doCanRun$0(ExecutionTargetManagerImpl.java:221)
	at com.intellij.execution.ExecutionTargetManagerImpl.doWithEachNonCompoundWithSpecifiedTarget(ExecutionTargetManagerImpl.java:279)
	at com.intellij.execution.ExecutionTargetManagerImpl.doCanRun(ExecutionTargetManagerImpl.java:209)
	at com.intellij.execution.ExecutionTargetManagerImpl.lambda$getTargetsFor$3(ExecutionTargetManagerImpl.java:258)
	at com.intellij.util.containers.ContainerUtil.findAll(ContainerUtil.java:1028)
	at com.intellij.util.containers.ContainerUtil.filter(ContainerUtil.java:1007)
	at com.intellij.execution.ExecutionTargetManagerImpl.getTargetsFor(ExecutionTargetManagerImpl.java:258)
	at com.intellij.execution.ExecutionTargetManagerImpl.updateActiveTarget(ExecutionTargetManagerImpl.java:145)
	at com.intellij.execution.ExecutionTargetManagerImpl.updateActiveTarget(ExecutionTargetManagerImpl.java:140)
	at com.intellij.execution.ExecutionTargetManagerImpl.access$100(ExecutionTargetManagerImpl.java:28)
	at com.intellij.execution.ExecutionTargetManagerImpl$2.runConfigurationSelected(ExecutionTargetManagerImpl.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:354)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:343)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:327)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:320)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:192)
	at com.sun.proxy.$Proxy58.runConfigurationSelected(Unknown Source)
	at com.intellij.execution.impl.RunManagerImpl.setSelectedConfiguration(RunManagerImpl.kt:449)
	at name.admitriev.jhelper.task.TaskUtils.createConfigurationForTask(TaskUtils.java:83)
	at name.admitriev.jhelper.task.TaskUtils.saveNewTask(TaskUtils.java:37)
	at name.admitriev.jhelper.actions.AddTaskAction.performAction(AddTaskAction.java:30)
	at name.admitriev.jhelper.actions.BaseAction.actionPerformed(BaseAction.java:15)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:260)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:277)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:183)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:147)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:411)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:723)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:367)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by AlexeyDmitriev** [comment]
I have not tried 2019.1 yet, I'll look into it.

**Comment by AlexeyDmitriev** [comment]
I've uploaded version 0.16.2 which fixes the issue for me. Please let me know if that doesn't fix the issue for you or if it reappears. Note this version will be available only for todays version and newer

The problem was in the API change
