### ISSUE TITLE
Plugin is not generating template files.

### ISSUE THREAD

**Issue by lazyboson** [AlexeyDmitriev/JHelper#137]
CLion Version - 2021.2 
JHelper version - latest

I have created the project and I have assigned configuration settings as per wiki instructions. But when I try to parse a problem from competitive companion, The submission.template and run.template files are not generating. Further I am getting following error - 
`name.admitriev.jhelper.exceptions.NotificationException: Couldn't open output file as document
	at name.admitriev.jhelper.generation.FileUtils.writeToFile(FileUtils.java:100)
	at name.admitriev.jhelper.generation.TemplatesUtils.createTemplateFromDefault(TemplatesUtils.java:70)
	at name.admitriev.jhelper.generation.TemplatesUtils.getTemplate(TemplatesUtils.java:43)
	at name.admitriev.jhelper.task.TaskUtils.getTaskContent(TaskUtils.java:31)
	at name.admitriev.jhelper.task.TaskUtils.generateCPP(TaskUtils.java:56)
	at name.admitriev.jhelper.task.TaskUtils.saveNewTask(TaskUtils.java:38)
	at name.admitriev.jhelper.components.ChromeParser.lambda$projectOpened$0(ChromeParser.java:98)
	at name.admitriev.jhelper.network.SimpleHttpServer.lambda$run$0(SimpleHttpServer.java:55)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

I am attaching ![Screenshot (3)](https://user-images.githubusercontent.com/63603603/141247506-1bad9554-283e-49cf-9598-77810f3ff690.png) and configuration settings ![Screenshot (4)](https://user-images.githubusercontent.com/63603603/141247516-8c7e69e0-93f7-4846-bed7-00ee48654777.png).

P.S. - I have tried to use your example project but things doesn't seem working for me.
Thanks

**Comment by AlexeyDmitriev** [comment]
As a workaround, I suggest you create the templates yourself (copying it from [the source](https://github.com/AlexeyDmitriev/JHelper/tree/master/resources/name/admitriev/jhelper/templates))

**Comment by lazyboson** [comment]
> As a workaround, I suggest you create the templates yourself (copying it from [the source](https://github.com/AlexeyDmitriev/JHelper/tree/master/resources/name/admitriev/jhelper/templates))

Thanks for workaround. It is working now.
